BEGIN;

DELETE FROM materials WHERE sku IN ('SYSTEMS','TRANSPORT','OPTICAL','FURUKAWA','NJ001M4','S124M4','S124M8','S124M12','S124M16','NJ001','S153A','S179','S178LDF','S184PM-SLDF','S185HS','S185PMLDF','S185PMROF','ACCESSORIES','S218R-PLUS','S251A','S326','IDENTIFIER','FERRULES','MT12SM-LL-PRE-ANGLED','FITELCLEAN','ULTRA-SLIM','APPLICATION','POLYETHYLENE','FUNDAMENTAL','ENVIRONMENTALLY','RESISTANT','SHIPBOARD','FLAME-RETARDANT','TECHNOLOGY','ELECTRIC','CABTYRE','SUPERCONDUCTORS','SUPERCONDUCTING','CONDENSATION','LOW-VOLTAGE','ELECTRICAL','CONNECTIONS','ACCESSORY','ASSEMBLY','MATERIALS','DIFFUSION','HEAT-PIPE','SLIDING','METAL','JUNCTION','BATTERY','PRECIOUS','SPECIAL','SOLDER-EROSION-FREE','HIGH-TENSION','COPPER-CLAD','ALUMINUM','PERFORMANCE','FAS-680','EFCUBE-820','EFTEC-550T','EFTEC-820','EFTEC-3','EFTEC-98BD','EFTEC-64T','EFTEC-97','EFTEC-98S','FREQUENCY','MICRO-CELLULAR','DIFFUSING','SEMICONDUCTOR','INSULATED','TEX-ECEW3','SILOXANE-FREE','DREDGING','CIRCUMFERENCE','IRRADIATION');

INSERT INTO materials (name, sku, "unitPrice", "stockQuantity") VALUES
('E-PON FTTH Systems','SYSTEMS',0,0),
('Transport Systems','TRANSPORT',0,0),
('Optical Fiber Sensing System','OPTICAL',0,0),
('Furukawa Optical Cable & Products','FURUKAWA',0,0),
('NJ001M4 Hand-Held Ribbon Fiber Fusion Splicer','NJ001M4',0,0),
('Ribbon Fiber Fusion Splicer S124M4','S124M4',0,0),
('Ribbon Fiber Fusion Splicer S124M8','S124M8',0,0),
('Ribbon Fiber Fusion Splicer S124M12','S124M12',0,0),
('Ribbon Fiber Fusion Splicer S124M16','S124M16',0,0),
('FITEL NINJA NJ001 Hand-Held Single Fiber Fusion Splicer','NJ001',0,0),
('S153A Hand Held Active Alignment Splicer','S153A',0,0),
('S179 Hand-Held, Core-Alignment Fusion Splicer','S179',0,0),
('S178LDF Core Alignment Large Diameter Fiber Fusion Splicer','S178LDF',0,0),
('S183PM II ver.2/S184PM-SLDF ver.2 Fusion Splicer','S184PM-SLDF',0,0),
('S185HS/S185PM High-end Fusion Splicer','S185HS',0,0),
('S185LDF/S185PMLDF High-end Fusion Splicer','S185PMLDF',0,0),
('S185ROF/S185PMROF High-end Fusion Splicer','S185PMROF',0,0),
('FITEL Fusion Splicer Accessories and Consumables','ACCESSORIES',0,0),
('S218R-Plus Optical Fiber Stripper','S218R-PLUS',0,0),
('S251A Optical Fiber Stripper','S251A',0,0),
('S326 High Precision Optical Fiber Cleaver','S326',0,0),
('Optical Fiber Identifier ID-H/R v3','IDENTIFIER',0,0),
('MT Ferrules','FERRULES',0,0),
('MT12SM-LL-Pre-Angled Ferrule','MT12SM-LL-PRE-ANGLED',0,0),
('Optical Connector Cleaner FITELCLEAN','FITELCLEAN',0,0),
('Ultra-Slim Cable with Extremely High Core Density','ULTRA-SLIM',0,0),
('Optical Fiber Loose Tube Cable (Armored Structure for Direct Buried Application)','APPLICATION',0,0),
('Optical Fiber Loose Tube Cable (Laminated Aluminum Polyethylene Sheath Structure for Duct Application)','POLYETHYLENE',0,0),
('Optical Fiber Loose Tube Cable (Fundamental Structures)','FUNDAMENTAL',0,0),
('Environmentally Friendly Wires for Electronic and Electrical Equipment ECOBEAMEX / ECOACE Series','ENVIRONMENTALLY',0,0),
('Heat Resistant Wires and Cables','RESISTANT',0,0),
('Offering of Offshore & Marine Shipboard Products','SHIPBOARD',0,0),
('Non-Halogen, Flame-Retardant, Flexible, Cross-Linked Polyethylene Insulated Electric Wire, EM-LMFC','FLAME-RETARDANT',0,0),
('Power Cable & Technology','TECHNOLOGY',0,0),
('Water Cooled Cable for Electric Furnace','ELECTRIC',0,0),
('Rubber Cabtyre Cable TRACAB','CABTYRE',0,0),
('Low Temperature Superconductors','SUPERCONDUCTORS',0,0),
('Superconducting Technologies for Smart Grids','SUPERCONDUCTING',0,0),
('Preventing dew condensation ''Drykeeper''','CONDENSATION',0,0),
('Insulating Protecting Covers for Low-Voltage Cable Joints ''Eftouch Covers''','LOW-VOLTAGE',0,0),
('Furukawa Electric Tape for Electrical Uses','ELECTRICAL',0,0),
('Insulate Electric Wire and Cable Connections ''Quick F-CO''','CONNECTIONS',0,0),
('Optical Cable and Accessory for TV Camera','ACCESSORY',0,0),
('Smart HDTV Assembly Checker','ASSEMBLY',0,0),
('Copper and Copper Alloy Wire Materials','MATERIALS',0,0),
('Total Thermal Solution, Heat Diffusion and Cooling Products','DIFFUSION',0,0),
('Micro Heat-Pipe HP-HS','HEAT-PIPE',0,0),
('Sliding Door Harness','SLIDING',0,0),
('Metal Core PCB','METAL',0,0),
('Metal Core PCB Junction Box','JUNCTION',0,0),
('Battery State Sensor','BATTERY',0,0),
('Precious Metal Stripe and Spot Plated Strip','PRECIOUS',0,0),
('Special Magnet Wire,  Ribbon Wires','SPECIAL',0,0),
('Special Magnet Wire, Solder-Erosion-Free Magnet Wire','SOLDER-EROSION-FREE',0,0),
('Special Magnet Wire, High-Tension Magnet Wire','HIGH-TENSION',0,0),
('Copper-Clad Aluminum Wire / Ribbon Wire','COPPER-CLAD',0,0),
('Special Magnet Wire, Aluminum Wire','ALUMINUM',0,0),
('High Performance Copper Alloy for Connectors EFCUBE-ST','PERFORMANCE',0,0),
('High Performance Copper Alloy for Automotive Connectors FAS-680/FAS-820','FAS-680',0,0),
('High Performance Copper Alloy for Connectors EFCUBE-820','EFCUBE-820',0,0),
('High Electrical Conductive and Heat Resistance Copper Alloy EFTEC-550T/550E','EFTEC-550T',0,0),
('High Performance Copper Alloy for Connectors EFTEC-820','EFTEC-820',0,0),
('High Performance Copper Alloy for Leadframes EFTEC-3','EFTEC-3',0,0),
('High-Performance Copper Alloy Bar for Connector Pins EFTEC-98BD','EFTEC-98BD',0,0),
('High Performance Copper Alloy for Leadframe EFTEC-64T, 64T-C','EFTEC-64T',0,0),
('High Performance Copper Alloy for Electrical Connectors EFTEC-97','EFTEC-97',0,0),
('High Performance Copper Alloy for Electrical Connectors EFTEC-98S','EFTEC-98S',0,0),
('High Frequency Printed Wiring Board','FREQUENCY',0,0),
('Micro-cellular Foamed PET Sheet "MCPET"','MICRO-CELLULAR',0,0),
('Diffusing MCPET Cap','DIFFUSING',0,0),
('Tapes for Semiconductor Process','SEMICONDUCTOR',0,0),
('Class E Triple Insulated Winding Wire TEX-E','INSULATED',0,0),
('Class E Triple Insulated Winding Wire TEX-ECEW3','TEX-ECEW3',0,0),
('Siloxane-Free Heat-Transfer Medium, F-CO TM Sheet','SILOXANE-FREE',0,0),
('Pipe Floater for Dredging Wooky','DREDGING',0,0),
('Whole Circumference Irradiation Optical Fiber Probe [Quartz]','CIRCUMFERENCE',0,0),
('Side Irradiation Optical Fiber Probe [Quartz]','IRRADIATION',0,0);

COMMIT;
